#ifndef ITEMSHAPEBASE_GLOBAL_H
#define ITEMSHAPEBASE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ITEMSHAPEBASE_LIBRARY)
#  define ITEMSHAPEBASESHARED_EXPORT Q_DECL_EXPORT
#else
#  define ITEMSHAPEBASESHARED_EXPORT 
#endif

#endif // ITEMSHAPEBASE_GLOBAL_H
